[package]
name = "dioxus_web"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
dioxus = { workspace = true, features = ["router", "fullstack"] }
dioxus-web-lib = { package = "dioxus-web", version = "0.7.2" }
ui = { path = "../ui" }
web-sys = { version = "0.3.83", optional = true }

[features]
default = []
web = ["dioxus/web", "dep:web-sys"]
server = ["dioxus/server", "ui/server"]
